Traceback (most recent call last):
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# continued from the previous code cell
# a bracket obtained in the previous code cell is used here

def bisection(x1,x2,rtol,nmax):
# function that finds a root in a given bracket
# input: x1, x2 = bracket
#        rtol = tolerance for f(x)
#        nmax = maximum itertation
# output: array of the followings:
#        root = root found by the bisection method
#        func = the function value at the root
#           n = the number of iteration
#
    f1 = f(x1)
    f2 = f(x2)

    # iteration counter
    n=0

    # mid point
    xm = (x1+x2)/2.0
    fm = f(xm)

    while abs(fm) > rtol and n < nmax:
        if f1*fm < 0:  # root in the lower half
            x2=xm
            f2=fm
        else:          # root in the upper half
            x1=xm
            f1=fm

        xm = (x1+x2)/2.0      # new mid point
        fm = f(xm)
        n+=1

    return [xm, fm ,n]

# main routine starts here

# set a tolerance
rtol = 1.e-6

# setr maximum iteration
nmax = 100
   
for k in range(3):
    [root, func, n]=bisection(xL[k],xU[k],rtol,nmax)
    print("root= {0:10.7e}, f(x)= {1:15.8e}, iteration= {2:3d}".format(root, func, n))

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 47[0m
[1;32m     44[0m nmax [38;5;241m=[39m [38;5;241m100[39m
[1;32m     46[0m [38;5;28;01mfor[39;00m k [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m3[39m):
[0;32m---> 47[0m     [root, func, n][38;5;241m=[39mbisection([43mxL[49m[k],xU[k],rtol,nmax)
[1;32m     48[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mroot= [39m[38;5;132;01m{0:10.7e}[39;00m[38;5;124m, f(x)= [39m[38;5;132;01m{1:15.8e}[39;00m[38;5;124m, iteration= [39m[38;5;132;01m{2:3d}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(root, func, n))

[0;31mNameError[0m: name 'xL' is not defined

