Traceback (most recent call last):
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# We use sympy package
from sympy import symbols, poly, laguerre

# this function computes abscissas and weights for ginve n
def laguerre_weights_roots(n):
    x = symbols("x")
    roots = poly(laguerre(n, x)).all_roots()
    
    w_i = [(rt / ((n + 1) * laguerre(n + 1, rt)) ** 2).evalf(20) for rt in roots]
    return x_i, w_i

# set the number of abscissas
n=4

# compute all abscissas and weights
[x,w]=laguerre_weights_roots(n)

# print out the results
print(" {0:^3} {1:^25} {2:^25}".format("i","x_i","w_i"))
for i in range(n):
    print("{0:3d} {1:25.19e} {2:25.19e}".format(i,x[i],w[i]))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 16[0m
[1;32m     13[0m n[38;5;241m=[39m[38;5;241m4[39m
[1;32m     15[0m [38;5;66;03m# compute all abscissas and weights[39;00m
[0;32m---> 16[0m [x,w][38;5;241m=[39m[43mlaguerre_weights_roots[49m[43m([49m[43mn[49m[43m)[49m
[1;32m     18[0m [38;5;66;03m# print out the results[39;00m
[1;32m     19[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m [39m[38;5;132;01m{0:^3}[39;00m[38;5;124m [39m[38;5;132;01m{1:^25}[39;00m[38;5;124m [39m[38;5;132;01m{2:^25}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat([38;5;124m"[39m[38;5;124mi[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mx_i[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mw_i[39m[38;5;124m"[39m))

Cell [0;32mIn[2], line 10[0m, in [0;36mlaguerre_weights_roots[0;34m(n)[0m
[1;32m      7[0m roots [38;5;241m=[39m poly(laguerre(n, x))[38;5;241m.[39mall_roots()
[1;32m      9[0m w_i [38;5;241m=[39m [(rt [38;5;241m/[39m ((n [38;5;241m+[39m [38;5;241m1[39m) [38;5;241m*[39m laguerre(n [38;5;241m+[39m [38;5;241m1[39m, rt)) [38;5;241m*[39m[38;5;241m*[39m [38;5;241m2[39m)[38;5;241m.[39mevalf([38;5;241m20[39m) [38;5;28;01mfor[39;00m rt [38;5;129;01min[39;00m roots]
[0;32m---> 10[0m [38;5;28;01mreturn[39;00m [43mx_i[49m, w_i

[0;31mNameError[0m: name 'x_i' is not defined

